language: ruby
before_install:
  - gem install bundler -v '>= 1.5.1'
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.4
  - 2.3.0
gemfile:
  - Gemfile
  - gemfiles/Gemfile-rails.3.2.x
  - gemfiles/Gemfile-rails.4.0.x
  - gemfiles/Gemfile-rails.4.1.x
matrix:
  exclude:
    - rvm: 2.2.4
      gemfile: gemfiles/Gemfile-rails.3.2.x
    - rvm: 2.3.0
      gemfile: gemfiles/Gemfile-rails.3.2.x
notifications:
  email: true
before_script:
  - npm install mjml@1.3.4